**First save a copy of this notebook in your Google drive.** Read this notebook from top to bottom and fill in the code as you go. Work together with your partner and discuss with other students in the class. Try to resolve any errors on your own first, but don't get stuck; ask for help!

For many of these questions, there are several ways to do it in Pandas. You only need to choose one that works. But you might want to experiment with multiple ways of doing the same thing to get practice working with Pandas.

## Titanic Data

 The Titanic data set (https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv) contains information about 2206 passengers and crew members that were aboard the RMS Titanic when it sank on April 15, 1912.

1\. Read in the Titanic data set. What seems to be the observational unit?

In [1]:
import pandas as pd

In [2]:
# YOUR CODE HERE - ADD AS MANY CELLS AS YOU WANT
titanic_df = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv")
titanic_df.head()

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN

2\. What column seems to be an appropriate index for this data frame? Can you think of any problems with using this column as the index?

name or ticket number would be ideal. There are duplicates of each, and crew do not have ticket numbers.

3\. Regardless of your answer to the previous question, write code to make "name" the index of the data frame.

In [3]:
titanic_df.set_index("name", inplace=True)

 4\. Write code that returns the observations for  "Kelly, Mr. James". What do you notice? (You can also try "Green, Mr. George"). Note: you might try this both with "name" as the index and with it not as the index.

In [4]:
james_kelly = titanic_df.loc['Kelly, Mr. James']
james_kelly

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
name,,,,,,,,,,
"Kelly, Mr. James",male,19.0,3rd,S,Scotland,363592.0,8.0100,0,3.0,NaN
"Kelly, Mr. James",male,44.0,3rd,Q,Ireland,330911.0,7.1607,0,3.0,NaN
"Kelly, Mr. James",male,44.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew

5\. Write code to extract a single `DataFrame` containing the observations three members of the Widener family:
  - Widener, Mr. George Dunton
  - Widener, Mr. Harry Elkins
  - Widener, Mrs. Eleanor

What became of them? Using a search engine, what else can you learn about them? (Note: you could just provide a list of these names. But you might also want to experiment with functions for working with strings, e.g., [`str.contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html) to find all instances of "Widener"; in this case, it might be helpful to have name as a regular column and not the index.)

The men died and Eleanor survived.

In [5]:
wideners = titanic_df.loc[titanic_df.index.str.contains("Widener")]
wideners

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
name,,,,,,,,,,
"Widener, Mr. George Dunton",male,50.0,1st,S,United States,113503.0,211.1,0,1.0,NaN
"Widener, Mr. Harry Elkins",male,27.0,1st,S,United States,113503.0,211.1,0,1.0,NaN
"Widener, Mrs. Eleanor",female,50.0,1st,S,United States,113503.0,211.1,1,1.0,NaN

6\. Look at a few rows in the full data set. Try to identify what each variable measures. Also, try to identify each variable as either quantitative, categorical, or other. (In general, there should be a code book with information about all the variables. But try to infer what you can from context.)

7\. The variable `pclass` measures the class for passengers. Why are some of the values in this column `NaN`? Should this variable be categorical or quantitative? What type does Pandas this it is?

The NaN values are crew members. It should be categorical as there is a fixed number of classes and they refer to groups of passengers.

In [6]:
print(titanic_df.dtypes)

gender       object
age         float64
class        object
embarked     object
country      object
ticketno    float64
fare        float64
survived      int64
pclass      float64
crew         object
dtype: object

8\. Write code to cast `pclass` to the correct type. Repeat for any other variables that do not have the correct type.

In [7]:
titanic_df['class'] = titanic_df['class'].astype('category')
titanic_df['pclass'] = titanic_df['pclass'].astype('category')
titanic_df['survived'] = titanic_df['survived'].astype('boolean')
titanic_df['gender'] = titanic_df['gender'].astype('category')
titanic_df['crew'] = titanic_df['crew'].astype('category')

## Transforming Categorical Variables

A categorical variable can be transformed by mapping its levels to new levels. For example, we may only be interested in whether a person on the titanic was a passenger or a crew member. The variable `class` is too detailed for these purposes. We can create a new variable, `type`, that is derived from the existing variable `class`. Observations with a `class` of "1st", "2nd", or "3rd" get a value of "passenger", while observations with a `class` of "deck crew", "engineering crew", or "deck crew" get a value of "crew".

In [8]:
titanic_df["type"] = titanic_df["class"].map({
    "1st": "passenger",
    "2nd": "passenger",
    "3rd": "passenger",
    "victualling crew": "crew",
    "engineering crew": "crew",
    "deck crew": "crew"
})

titanic_df

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type
name,,,,,,,,,,,
"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,False,3.0,NaN,passenger
"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger
"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger
"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,True,3.0,NaN,passenger
"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,True,3.0,NaN,passenger
...,...,...,...,...,...,...,...,...,...,...,...
"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,True,NaN,deck crew,crew
"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,True,NaN,victualling crew,crew
"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,False,NaN,engineering crew,crew
"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,NaN
"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,NaN

Upon closer inspection of this `DataFrame`, we see that we accidentally left out the level "restaurant staff" in the input to `.map()`. Any levels that are unspecified will be mapped to the missing value `NaN`.

This suggests a more concise way to define the new variable `type`. We can specify only the levels for passengers in the mapping and then fill in the missing values afterwards.

In [9]:
titanic_df["type"] = titanic_df["class"].map({
    "1st": "passenger",
    "2nd": "passenger",
    "3rd": "passenger"
})

# Replace all missing values by "crew"
titanic_df["type"].fillna("crew", inplace=True)

titanic_df

<positron-console-cell-9>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type
name,,,,,,,,,,,
"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,False,3.0,NaN,passenger
"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger
"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger
"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,True,3.0,NaN,passenger
"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,True,3.0,NaN,passenger
...,...,...,...,...,...,...,...,...,...,...,...
"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,True,NaN,deck crew,crew
"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,True,NaN,victualling crew,crew
"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,False,NaN,engineering crew,crew
"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,crew
"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,crew

For more complex mappings, the `.map()` method also accepts a function. So the above is equivalent to

In [10]:
def class_to_type(c):
  if c in ["1st", "2nd", "3rd"]:
    return "passenger"
  else:
    return "crew"

titanic_df["class"].map(class_to_type)

name
Abbing, Mr. Anthony               passenger
Abbott, Mr. Eugene Joseph         passenger
Abbott, Mr. Rossmore Edward       passenger
Abbott, Mrs. Rhoda Mary 'Rosa'    passenger
Abelseth, Miss. Karen Marie       passenger
                                    ...
Wynn, Mr. Walter                       crew
Yearsley, Mr. Harry                    crew
Young, Mr. Francis James               crew
Zanetti, Sig. Minio                    crew
Zarracchi, Sig. L.                     crew
Name: class, Length: 2207, dtype: object

## Converting Quantitative Variables to Categorical Variables

Sometimes it is necessary to categorize quantitative variables. We can use the `cut` function in `pandas` to categorize or bin a quantitative variable, by specifying the endpoints of the bins. We can also provide labels for the bins.

In [11]:
titanic_df["age_categories"] = pd.cut(x = titanic_df["age"],
                                      bins = [0, 18, 30, 45, 65, 130],
                                      labels = ["<18", "18-30", "30-45", "45-65", "65+"])

titanic_df

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type,age_categories
name,,,,,,,,,,,,
"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,False,3.0,NaN,passenger,30-45
"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger,<18
"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger,<18
"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,True,3.0,NaN,passenger,30-45
"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,True,3.0,NaN,passenger,<18
...,...,...,...,...,...,...,...,...,...,...,...,...
"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,True,NaN,deck crew,crew,30-45
"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,True,NaN,victualling crew,crew,30-45
"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,False,NaN,engineering crew,crew,30-45
"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,crew,18-30
"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,crew,18-30

Now we can treat the new variable as we would any other categorical variable.

In [12]:
titanic_df["age_categories"]

name
Abbing, Mr. Anthony               30-45
Abbott, Mr. Eugene Joseph           <18
Abbott, Mr. Rossmore Edward         <18
Abbott, Mrs. Rhoda Mary 'Rosa'    30-45
Abelseth, Miss. Karen Marie         <18
                                  ...
Wynn, Mr. Walter                  30-45
Yearsley, Mr. Harry               30-45
Young, Mr. Francis James          30-45
Zanetti, Sig. Minio               18-30
Zarracchi, Sig. L.                18-30
Name: age_categories, Length: 2207, dtype: category
Categories (5, object): ['<18' < '18-30' < '30-45' < '45-65' < '65+']

Arguments to the `cut` method can be specified to determine the treatment of the bin endpoints, but we won't go into the details here. There is also a `qcut` method which creates bins based on quantiles (e.g., the endpoints are the 25th, 50th, and 75th percentiles (along with the min and max).)

## Back to the Exercises about the Titanic data...

10\. Create a new country column that contains only the values United States, United Kingdom, or Other. (At the time of the Titanic, the countries in the United Kingdom were England, Scotland, Wales, and Ireland, including what is now Northern Ireland.) Don't overwrite the original country column.

In [13]:
def country_to_countrycat(c):
  if c in ["United States", "United Kingdom"]:
    return c
  else:
    return "Other"

titanic_df["countrycat"] = titanic_df["country"].map(country_to_countrycat)
titanic_df["countrycat"]

name
Abbing, Mr. Anthony               United States
Abbott, Mr. Eugene Joseph         United States
Abbott, Mr. Rossmore Edward       United States
Abbott, Mrs. Rhoda Mary 'Rosa'            Other
Abelseth, Miss. Karen Marie               Other
                                      ...
Wynn, Mr. Walter                          Other
Yearsley, Mr. Harry                       Other
Young, Mr. Francis James                  Other
Zanetti, Sig. Minio                       Other
Zarracchi, Sig. L.                        Other
Name: countrycat, Length: 2207, dtype: object

11\. Create a new column that categorizes the fare variable into bins of length 5 from 0 to 25, bins of length 25 from 25 to 100, and 100+.

In [14]:
fare_max = titanic_df['fare'].max()
titanic_df["fare_bins"] = pd.cut(x = titanic_df["fare"],
                                      bins = [0, 5, 10, 15, 20, 25, 50, 75, 100, fare_max],
                                      labels = ["0-5", "5-10", "10-15", "15-20", "20-25","25-50","50-75","75-100","100+"])

titanic_df

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type,age_categories,countrycat,fare_bins
name,,,,,,,,,,,,,,
"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,False,3.0,NaN,passenger,30-45,United States,5-10
"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger,<18,United States,20-25
"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,False,3.0,NaN,passenger,<18,United States,20-25
"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,True,3.0,NaN,passenger,30-45,Other,20-25
"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,True,3.0,NaN,passenger,<18,Other,5-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,True,NaN,deck crew,crew,30-45,Other,NaN
"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,True,NaN,victualling crew,crew,30-45,Other,NaN
"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,False,NaN,engineering crew,crew,30-45,Other,NaN
"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,crew,18-30,Other,NaN
"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,False,NaN,restaurant staff,crew,18-30,Other,NaN

## Working with Gemini

Colab notebooks have [Gemini](), Google's AI, built in. Let's try it.

1\. Load either the Titanic data frame. After you load the data frame, there should be a button for "View recommended plot". Turn that button on and see what you get. Select one of the suggested plots that summarizes a single categorical variable. (Careful: make sure it's a single categorical variable. Some of the bar plots might be summarizing multiple variables.) What are features that you like about the plot? Are there any features you don't like?

I could not get this button to appear but was able to generate code with gemini. The design and layout features are nice.

In [15]:
df2 = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv")
df2

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2202,"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,1,NaN,deck crew
2203,"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,1,NaN,victualling crew
2204,"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew
2205,"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff
2206,"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff

2\. Now click on the "generate" with AI link, or the Gemini button. Write a prompt to reproduce some of your analysis from earlier in this notebook. You can copy and paste one of the questions, or you can try writing your own prompt. Run the code and examine the results. How successful was it?

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Resetting index to avoid 'duplicate labels' error in seaborn
plot_data = titanic_df.reset_index()

plt.figure(figsize=(10, 6))
sns.kdeplot(data=plot_data, x='age', hue='type', fill=True, common_norm=False, palette='muted', alpha=.5, linewidth=2)
plt.title('Comparison of Age Distribution: Passengers vs Crew')
plt.xlabel('Age')
plt.ylabel('Density')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Summary calculation
summary = titanic_df.groupby('type')['age'].describe()
print("Age Summary Statistics:")
print(summary)

Based on the plot, we can observe the following differences:
1. **Passengers** often have a wider distribution including many children (below 18).
2. **Crew** members are typically concentrated in the working-age range (20-50) with very few children or elderly individuals compared to passengers.